Remove `plugin = true` in Cargo.toml
Macros are not plugins. `plugin = true` causes this error when building a static library that (recursively) depends on debug-unreachable:

```
error: dependency `debug_unreachable` not found in rlib format
error: aborting due to previous error